// <auto-generated />
using System;
using DevCitySim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevCitySim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240916104324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevCitySim.Data.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = "Office",
                            Location = "NullStreet 1",
                            Name = "DevCityTech"
                        });
                });

            modelBuilder.Entity("DevCitySim.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<float>("Kilometers")
                        .HasColumnType("float");

                    b.Property<string>("NumberPlate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Mercedes",
                            Kilometers = 2000f,
                            NumberPlate = "XXL-889-WN"
                        });
                });

            modelBuilder.Entity("DevCitySim.Data.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Job")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2001, 10, 24, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Job = "Software Developer",
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2001, 10, 24, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Job = "Software Developer",
                            Name = "Doety Jane"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
